version: '3.9'

services:
  svprobase:
    image: ghcr.io/enablesecurity/svpro-docker/svprobase:latest
    build:
      context: base
  
  svpro:
    build:
      context: .
      args:
        - SVPRO_URL
        - SVPRO_DLFN=sipviciouspro-latest.zip
    network_mode: host
    pull_policy: never
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    volumes:
      - ./share:/home:rw
    working_dir: /home
